pipeline:
  build-dev:
    image: ubuntu
    commands:
      - docker build --build-arg WEB_ENV=dev -t my-image-dev .
    when:
      event: tag
      branch: '*'
      ref: refs/tags/dev.*
  build-prod:
    image: ubuntu
    commands:
      - docker build --build-arg WEB_ENV=prod -t my-image-prod .
    when:
      event: tag
      branch: '*'
      ref: refs/tags/prod.*
