pipeline:
  build-dev:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build --build-arg WEB_ENV=dev -t my-image-dev .
    when:
      event: tag
      branch: '*'
      ref: refs/tags/dev.*
    privileged: true
  build-prod:
    image: docker
    commands:
      - docker build --build-arg WEB_ENV=prod -t my-image-prod .
    when:
      event: tag
      branch: '*'
      ref: refs/tags/prod.*
    privileged: true
