pipeline:
  build-dev:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose -f docker-compose.dev.yml down
      - docker-compose -f docker-compose.dev.yml build
      - docker-compose -f docker-compose.dev.yml up -d
    when:
      event: tag
      branch: '*'
      ref: refs/tags/dev.*
    privileged: true
  build-prod:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose -f docker-compose.prod.yml down
      - docker-compose -f docker-compose.prod.yml build
      - docker-compose -f docker-compose.prod.yml up -d
    when:
      event: tag
      branch: '*'
      ref: refs/tags/prod.*
    privileged: true
