pipeline:
  build-dev:
    image: alpine
    commands:
      - apk add --no-cache rsync
      - rm -rf /usr/share/nginx/html/123/*
      - cp -r dist /usr/share/nginx/html/123
    when:
      event: tag
      branch: '*'
      ref: refs/tags/dev.*
    privileged: true
  build-prod:
    image: docker
    commands:
      - docker build --build-arg WEB_ENV=prod -t my-image-prod .
    when:
      event: tag
      branch: '*'
      ref: refs/tags/prod.*
    privileged: true
