pipeline:
  build-dev:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker stop astro1 && docker rm astro1
      - docker build --build-arg WEB_ENV=build:dev -t astro10  .
      - docker run -d -p 9000:80 --name astro1 -e WEB_ENV=build:dev astro10
    when:
      event: tag
      branch: '*'
      ref: refs/tags/dev.*
    privileged: true
  build-prod:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker stop astro2 && docker rm astro2
      - docker build --build-arg WEB_ENV=build:prod -t astro20  .
      - docker run -d -p 9001:80 --name astro2 -e WEB_ENV=build:prod astro20
    when:
      event: tag
      branch: '*'
      ref: refs/tags/prod.*
    privileged: true
