version: '3'
services:
  astro:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WEB_ENV: 'build:prod' # 'build:dev'
    container_name: astro1
    ports:
      - 9003:80 # 宿主机可以用 127.0.0.1:9000
